dbt_casestudy:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: mydb
      schema: dbttest
      threads: 1